In [29]:
paragraph = """
Defeat of the Sith (1032 BBY)

    1032 BBY[21]
        The Jedi-Sith War[81] ends with the Jedi Order and Republic forces victorious.[73]
            Coruscant and the Jedi Temple had been occupied by the Sith as part of the war[73] and the Darksaber stolen from the temple by Mandalorians.[74]
            Mandalore mural

        A Mandalorian mural depicts the slaying of a Jedi
        By this point, Coruscant and the Jedi Temple are liberated by Jedi and Republic forces.[73]
        The Brotherhood of Darkness,[82] an army of the Sith in which Darth Bane served,[83] are defeated by the Jedi's Army of Light[82] as a result of infighting amongst themselves.[84] The Sith, who once numbered thousands,[85] are driven into hiding[17] and are eventually thought extinct.[86]
    The sole Sith survivor, Darth Bane,[87] creates the Grand Plan—a plot to destroy the Jedi and the Republic from within for the coming of Sith rule over the galaxy[88]—and establishes the[89] Rule of Two,[36] a lineage of Sith who would operate in the shadows, preserving the Sith's vendetta against the Jedi whilst preparing for their own return. Centuries before the Clone Wars, the Rule of Two is revealed to the Jedi Order, though still they presume the Sith's eradication and believe that Bane's plan is ruined with his defeat[89] allegedly at the hands of his apprentice, Darth Zannah, in a duel on the Inner Rim planet Ambria. This pattern is repeated by nearly all Sith thereafter.[90]
    The Sith Lord becomes the last of his kind to be laid to rest on Moraband's Valley of the Dark Lords.[89]
    The Sith Wars waged between the Republic and the Sith Empire[91] has ended by this point.[92] The Sith Wars saw the participation of the Jedi Order on the side of the Republic[8] as well as the participation of the Chiss Ascendancy, which encountered multiple alien species before retreating to their borders.[91] The Jedi Cervil the Uncanny had left behind testimonies about lightwhips being effective against the Sith's Forbidden Forms,[93] and Ithorian population of Auratera continues restoring the world to its natural state following the Sith Wars.[8]

c. 1022 BBY

    The Amaxine warriors disappear from the known galaxy.[21]

c. 1000 BBY

    The Massassi become extinct.[21]
    The translation of Sith runes is outlawed.[21]
    In the aftermath of the Corsair Wars, Master Oo'ob breaks with Jedi doctrine, pursuing a pre-emptive method of dealing with threats to galactic peace. He and his partner, noted crystallist Var-Whill, develop the Farkiller, and use it to kill a number of "emergent" despots. Within the decade, the Jedi Council pronounces them apostate and eventually purges them,[94] with Oo'ob's expulsion taking place around 1000 BBY.[21]
"""

In [2]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [30]:
documents = nltk.sent_tokenize(paragraph)

In [31]:
import re
corpus = []
for i in documents:
    review = re.sub("[^a-zA-Z]"," ",i)
    review = review.lower()
    corpus.append(review)

In [32]:
corpus[0]

' defeat of the sith       bby            bby             the jedi sith war     ends with the jedi order and republic forces victorious '

In [33]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [34]:
stemmer = PorterStemmer()

In [35]:
cleaned_corpus = []
for s in corpus:
    words = nltk.word_tokenize(s)
    clean_words = [stemmer.stem(word) for word in words if word not in stopwords.words('english')]
    cleaned_corpus.append(" ".join(clean_words))

In [37]:
cleaned_corpus

['defeat sith bbi bbi jedi sith war end jedi order republ forc victori',
 'corusc jedi templ occupi sith part war darksab stolen templ mandalorian',
 'mandalor mural mandalorian mural depict slay jedi point corusc jedi templ liber jedi republ forc',
 'brotherhood dark armi sith darth bane serv defeat jedi armi light result infight amongst',
 'sith number thousand driven hide eventu thought extinct',
 'sole sith survivor darth bane creat grand plan plot destroy jedi republ within come sith rule galaxi establish rule two lineag sith would oper shadow preserv sith vendetta jedi whilst prepar return',
 'centuri clone war rule two reveal jedi order though still presum sith erad believ bane plan ruin defeat allegedli hand apprentic darth zannah duel inner rim planet ambria',
 'pattern repeat nearli sith thereaft',
 'sith lord becom last kind laid rest moraband valley dark lord',
 'sith war wage republ sith empir end point',
 'sith war saw particip jedi order side republ well particip chiss a

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv = CountVectorizer(binary=False,ngram_range=(3,3))

In [40]:
X = cv.fit_transform(corpus)

In [41]:
cv.vocabulary_

{'defeat of the': 78,
 'of the sith': 190,
 'the sith bby': 304,
 'sith bby bby': 242,
 'bby bby the': 39,
 'bby the jedi': 41,
 'the jedi sith': 290,
 'jedi sith war': 142,
 'sith war ends': 252,
 'war ends with': 347,
 'ends with the': 92,
 'with the jedi': 363,
 'the jedi order': 289,
 'jedi order and': 139,
 'order and republic': 201,
 'and republic forces': 15,
 'republic forces victorious': 225,
 'coruscant and the': 66,
 'and the jedi': 17,
 'the jedi temple': 291,
 'jedi temple had': 144,
 'temple had been': 267,
 'had been occupied': 109,
 'been occupied by': 45,
 'occupied by the': 172,
 'by the sith': 57,
 'the sith as': 303,
 'sith as part': 241,
 'as part of': 29,
 'part of the': 205,
 'of the war': 191,
 'the war and': 318,
 'war and the': 346,
 'and the darksaber': 16,
 'the darksaber stolen': 278,
 'darksaber stolen from': 71,
 'stolen from the': 262,
 'from the temple': 105,
 'the temple by': 315,
 'temple by mandalorians': 266,
 'mandalore mural mandalorian': 156,
 'm

In [49]:
corpus[0]

' defeat of the sith       bby            bby             the jedi sith war     ends with the jedi order and republic forces victorious '

In [51]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 

In [47]:
X[0].toarray().shape

(1, 370)

# TF-IDF

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [53]:
tf = TfidfVectorizer(binary=False)

In [54]:
X = tf.fit_transform(corpus)

In [55]:
tf.vocabulary_

{'defeat': 52,
 'of': 127,
 'the': 182,
 'sith': 170,
 'bby': 21,
 'jedi': 98,
 'war': 203,
 'ends': 68,
 'with': 211,
 'order': 132,
 'and': 10,
 'republic': 155,
 'forces': 78,
 'victorious': 201,
 'coruscant': 42,
 'temple': 179,
 'had': 84,
 'been': 25,
 'occupied': 126,
 'by': 34,
 'as': 16,
 'part': 136,
 'darksaber': 48,
 'stolen': 176,
 'from': 80,
 'mandalorians': 113,
 'mandalore': 111,
 'mural': 119,
 'mandalorian': 112,
 'depicts': 54,
 'slaying': 171,
 'this': 188,
 'point': 145,
 'are': 13,
 'liberated': 105,
 'brotherhood': 33,
 'darkness': 47,
 'an': 9,
 'army': 14,
 'in': 90,
 'which': 207,
 'darth': 49,
 'bane': 20,
 'served': 167,
 'defeated': 53,
 'light': 106,
 'result': 158,
 'infighting': 91,
 'amongst': 8,
 'themselves': 185,
 'who': 210,
 'once': 129,
 'numbered': 124,
 'thousands': 191,
 'driven': 60,
 'into': 93,
 'hiding': 88,
 'eventually': 71,
 'thought': 190,
 'extinct': 73,
 'sole': 172,
 'survivor': 177,
 'creates': 44,
 'grand': 83,
 'plan': 142,
 'plo

In [56]:
corpus[0]

' defeat of the sith       bby            bby             the jedi sith war     ends with the jedi order and republic forces victorious '

In [57]:
X[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.14517981, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.43363841, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.26323293, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.30007357, 0.        ,
        0.        , 0.        , 0.        , 0.  

In [58]:
tf = TfidfVectorizer(binary=False,max_features=10)

In [59]:
X = tf.fit_transform(corpus)

In [60]:
X[0].toarray()

array([[0.19473222, 0.5816468 , 0.        , 0.38946443, 0.17437294,
        0.26860344, 0.34874587, 0.40413879, 0.        , 0.2908234 ]])