In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'Its over Anakin, I have the high ground',
    'Hello there general kenobi',
    'the dark side of the force is all too powerful',
    'I have got a bad feeling about this',
     'I am a good developer',
     'understand the meaning of words',
     'may the force be with you']

In [27]:
print("GPUs:", tf.config.list_physical_devices('GPU'))

GPUs: []


In [28]:
vocab_size = 10000

In [29]:
ohe_representation = [one_hot(words,vocab_size) for words in sent]

In [30]:
ohe_representation

[[5821, 8645, 7898, 850],
 [5821, 8645, 7898, 6732],
 [5821, 3487, 7898, 9456],
 [3102, 2802, 8911, 437, 6795, 5821, 4469, 7612],
 [3377, 1915, 1992, 2458],
 [5821, 6148, 7720, 7898, 5821, 6419, 6321, 8184, 2046, 6655],
 [437, 6795, 3964, 3299, 6827, 5472, 4319, 1525],
 [437, 1618, 3299, 165, 8694],
 [7184, 5821, 7723, 7898, 974],
 [1634, 5821, 6419, 4537, 7706, 8015]]

In [31]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [32]:
sent_length = 12

In [33]:
embedded_rep = pad_sequences(ohe_representation,padding='pre',maxlen=sent_length)

In [35]:
print(embedded_rep)

[[   0    0    0    0    0    0    0    0 5821 8645 7898  850]
 [   0    0    0    0    0    0    0    0 5821 8645 7898 6732]
 [   0    0    0    0    0    0    0    0 5821 3487 7898 9456]
 [   0    0    0    0 3102 2802 8911  437 6795 5821 4469 7612]
 [   0    0    0    0    0    0    0    0 3377 1915 1992 2458]
 [   0    0 5821 6148 7720 7898 5821 6419 6321 8184 2046 6655]
 [   0    0    0    0  437 6795 3964 3299 6827 5472 4319 1525]
 [   0    0    0    0    0    0    0  437 1618 3299  165 8694]
 [   0    0    0    0    0    0    0 7184 5821 7723 7898  974]
 [   0    0    0    0    0    0 1634 5821 6419 4537 7706 8015]]


In [36]:
dim = 12

In [49]:
model = Sequential()
model.add(Embedding(vocab_size,12,input_length=sent_length))
model.compile('adam','mse')

C:\Users\tejas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [50]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [51]:
print(embedded_rep[0])

[   0    0    0    0    0    0    0    0 5821 8645 7898  850]


In [52]:
model.predict(embedded_rep[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step


array([[ 0.03452325,  0.00290419, -0.0478727 , -0.04927165, -0.00973719,
         0.04983038,  0.02878049,  0.03144518, -0.01323439, -0.00996486,
         0.0091214 ,  0.0397067 ],
       [ 0.03452325,  0.00290419, -0.0478727 , -0.04927165, -0.00973719,
         0.04983038,  0.02878049,  0.03144518, -0.01323439, -0.00996486,
         0.0091214 ,  0.0397067 ],
       [ 0.03452325,  0.00290419, -0.0478727 , -0.04927165, -0.00973719,
         0.04983038,  0.02878049,  0.03144518, -0.01323439, -0.00996486,
         0.0091214 ,  0.0397067 ],
       [ 0.03452325,  0.00290419, -0.0478727 , -0.04927165, -0.00973719,
         0.04983038,  0.02878049,  0.03144518, -0.01323439, -0.00996486,
         0.0091214 ,  0.0397067 ],
       [ 0.03452325,  0.00290419, -0.0478727 , -0.04927165, -0.00973719,
         0.04983038,  0.02878049,  0.03144518, -0.01323439, -0.00996486,
         0.0091214 ,  0.0397067 ],
       [ 0.03452325,  0.00290419, -0.0478727 , -0.04927165, -0.00973719,
         0.04983038,  